# Generated by Django 2.0.5 on 2018-08-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='city',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='state',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
