# Generated by Django 2.0.5 on 2018-08-21 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180819_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='user',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
    ]
